security:
    encoders:
        OnTheRoad\OnTheRoadBundle\Entity\TUser: plaintext
    role_hierarchy:
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       ROLE_USER
    providers: 
        main:        
            entity:          
                class: 	OnTheRoad\OnTheRoadBundle\Entity\TUser
                property: nameuser
    firewalls: 
        dev:   
            pattern:  ^/(_(profiler|wdt)|css|images|js)/  
            security: false 
        login:     
            pattern:  ^login$
            security: false  
                        
        secured_area:  
            pattern:    ^/
            form_login:  
                check_path: /check
                login_path: /login
            logout:  
                path:   /logout
                target: /
            anonymous: ~    
    access_control:   
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/en/comments/new, roles: ROLE_USER }
        #- { path: ^/es/comments/new, roles: ROLE_USER }